ALTER TABLE "politicos"
ADD COLUMN IF NOT EXISTS "id_legislatura" SMALLINT,
ADD COLUMN IF NOT EXISTS "data_ultimo_status" DATE,
ADD COLUMN IF NOT EXISTS "nome_eleitoral" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "condicao_eleitoral" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "url_website" TEXT,
ADD COLUMN IF NOT EXISTS "redes_sociais" TEXT,
ADD COLUMN IF NOT EXISTS "escolaridade" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "municipio_nascimento" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "uf_nascimento" VARCHAR(2),
ADD COLUMN IF NOT EXISTS "gabinete_nome" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "gabinete_predio" VARCHAR(20),
ADD COLUMN IF NOT EXISTS "gabinete_sala" VARCHAR(20),
ADD COLUMN IF NOT EXISTS "gabinete_andar" VARCHAR(20);
